CREATE DATABASE IF NOT EXISTS luis_bd CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE luis_bd;

CREATE TABLE IF NOT EXISTS tasks(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed TINYINT(1) DEFAULT 0,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);